server: github.com
org: YunoHost-Apps

super-maintainers: super-maintainers

repositories:
  - # Filter-out .github repository of other matches
    include: ['.github']

  - include: ['endi_ynh']
    exclude: []
    default: master
    branches:
      master: full_protection
      testing: protection_allow_force_push


rulesets:
  full_protection:
    branch_protection:
      required_status_checks:
        strict: false
        checks: [] #TODO: That is where we would require CI checks

      enforce_admins: true

      required_pull_request_reviews:
        dismissal_restrictions:
          users: [] # "@maintainers"
          teams: [] # ["@super-maintainers"]
        required_approving_review_count: 1
        bypass_pull_request_allowances:
          users: [] # "@maintainers"
          teams: [] # ["@super-maintainers"]

      restrictions:
        users: [] # "@maintainers"
        teams: [] # ["@super-maintainers"]

      allow_force_pushes: false

    required_signatures: false

  protection_allow_force_push:
    branch_protection:
      required_status_checks:
        strict: false
        checks: [] #TODO: That is where we would require CI checks

      enforce_admins: true

      required_pull_request_reviews:
        dismissal_restrictions:
          users: [] # "@maintainers"
          teams: [] # ["@super-maintainers"]
        required_approving_review_count: 1
        bypass_pull_request_allowances:
          users: [] # "@maintainers"
          teams: [] # ["@super-maintainers"]

      restrictions:
        users: [] # "@maintainers"
        teams: [] # ["@super-maintainers"]

      allow_force_pushes: true

    required_signatures: false
